apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-jobmanager-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: {{ .Values.name }}
    component: jobmanager